# Generated by Django 5.1 on 2024-08-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='birth_date',
            new_name='date_of_birth',
        ),
    ]
