# Generated by Django 5.1 on 2024-09-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_image_id_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_id',
            field=models.CharField(default='2ff8afa297854f3d9f8a6eccf83c7d4d', editable=False, max_length=32, unique=True),
        ),
    ]
