# Generated by Django 5.1 on 2024-09-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_itemincart_active_alter_product_image_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminwishlist',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_id',
            field=models.CharField(default='40b54d4f99f14c0199effbe5cee37088', editable=False, max_length=32, unique=True),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
