# Generated by Django 5.1 on 2024-09-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_iteminwishlist_active_alter_product_image_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_id',
            field=models.CharField(default='61f0fca4cb4042419520aa594d6de5b5', editable=False, max_length=32, unique=True),
        ),
    ]
