# Generated by Django 5.1 on 2024-09-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_id',
            field=models.CharField(default='b89386934e11471abd9a6b6458678ee2', editable=False, max_length=32, unique=True),
        ),
    ]
