# Generated by Django 5.1 on 2024-09-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_id',
            field=models.CharField(default='619234c6e308497f8a2718bdea23dfab', editable=False, max_length=32, unique=True),
        ),
    ]
