# Generated by Django 5.1 on 2024-09-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_product_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_id',
            field=models.CharField(default='4bdb4a55e0e644838f2eade29e805065', editable=False, max_length=32, unique=True),
        ),
    ]
