# Generated by Django 5.1 on 2024-09-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_product_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_id',
            field=models.CharField(default='ed4150f9ee8b4c5bb98a00edea614959', editable=False, max_length=32, unique=True),
        ),
    ]
