# Generated by Django 5.1 on 2024-09-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_image_id_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_id',
            field=models.CharField(default='fa3973e80f31476fa6f1e48a2880bd9f', editable=False, max_length=32, unique=True),
        ),
    ]
